### ISSUE TITLE
Error Running GBM with additional variable

### ISSUE THREAD

**Issue by JeroneGagliano** [LBNL-ETA/RMV2.0#10]
I added a days_off column to my data file that currently works using the GBM.  I used zeros and ones to note whether the given timestamp was part of the normal operation days (1) or lower use operation (0). I have also had success running this file in RMV2 interface and selecting a days_off csv file that lists the dates that correspond to zeros, the low use periods. 
Through the R console, I used the given command with the defaults parameter settings, but then get the following error:
>gbm_obj <- gbm_baseline(train_path = "C:/Users/Jerone/Documents/BldgA_Elec-kW.csv", variables = c("Temp","tow","days_off"))

Error in cut.default(y, breaks, include.lowest = TRUE) : 
  invalid number of intervals

I tried changing some of the parameters but had the same error. Is this a bug? Do I need to change certain parameters? I have attached my file.

[BldgA_Elec-kW.zip](https://github.com/LBNL-ETA/RMV2.0/files/1778125/BldgA_Elec-kW.zip)

**Comment by samirtouzani** [comment]
You have a date format issue in your csv file (year as "2017" rather than "17"). My guess is that you have probably opened the file in excel and it changed the format. It already happened to me. 

This should do the work:

Data<-read.csv(file = "C:/Users/Jerone/Documents/BldgA_Elec-kW.csv")
dts <- as.POSIXct(strptime(Data$time, format = "%m/%d/%Y %H:%M"))
Data$time <- format(dts,"%m/%d/%y %H:%M")
gbm_obj <- gbm_baseline(train_Data = Data, variables = c("Temp","tow","days_off"))

**Comment by JeroneGagliano** [comment]
Hi Samir,

Interesting that this change to the date format allows the file to run
properly in the R Console.  As I mentioned before, this same file without
the days_off column runs just fine using the GBM through the R Console and
through the GUI. This issue can be closed. Please see my comment in the
email asking if/when the user will be able to import files that have
multiple variables in the GUI.

Thanks
Jerone



Jerone Gagliano, PE
607-592-4948
